name: comiko_backend
description: Comiko backend project.
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  comiko_shared:
    git: https://github.com/comiko-app/shared.git

dependency_overrides:
  comiko_shared:
    path: ../shared

dev_dependencies:
  test: ^0.12.0
