name: comiko_backend
description: Comiko backend project.
version: 0.0.1

dev_dependencies:
  build_runner: "^0.10.1+1"
  build_test: "0.10.3+1"
  test: "^1.3.0"

  comiko_shared:
    path: "../shared"


